### ISSUE TITLE
[QUESTION] Do i need the Software to Program the Keyboard on every PC?

### ISSUE THREAD

**Issue by WreckingBANG** [GEIGEIGEIST/TOTEM#39]
A important factor if i build myself the Totem is that i want to use it at work. If i install the Software on my PC at Home and configure my layers there, do i have all the keymaps working on my PC at work if i plug it in there, or would i need the software on all computers?

**Comment by spamwax** [comment]
layers are stored in the keyboard's MCU so they are independent of which computer the keyboard is connected to.

**Comment by WreckingBANG** [comment]
Thank you, that is what i wanted to hear!
