### ISSUE TITLE
Tenting support

### ISSUE THREAD

**Issue by ar-qun** [GEIGEIGEIST/TOTEM#6]
Hello GEIGEIGEIST,

I really liked you keyboard and was wondering if tenting is possible with this keyboard?

Would be interesting to use it with Manfrotto tripods.

Also would it be possible to buy a pre-build version?

**Comment by GEIGEIGEIST** [comment]
Hi ar-qun,
Unfortunately tenting isn't possible, since I couldn't fit the footprint for the SplitKB puck in my PCB, without making to many compromises.
A pre built version isn't planed, but at least a kit will be available soon.

**Comment by dlehman** [comment]
@GEIGEIGEIST Any idea what timeframe for kit will be? Considering ordering my own parts, but would be willing to wait a bit for a kit.

**Comment by Wanderwichtl** [comment]
@GEIGEIGEIST I am currently thinking about building a copy of your awesome Totem. Is it worth it to wait for the kit, and what will it include?
Would it be possible to make it to a wireless version on my own?
Will it include a (transparent) case? 
Will it be a standard PBC?
